class ItemsGoogle:
    item_path = sorted([
        {"path": "./assets/icons/display-config.png", "gdrive_id": "1fnqdm7mywGDptRn2dq7ezHzZEFQl1Jpr"},
        {"path": "./assets/icons/folder-download.png", "gdrive_id": "1F9uZUwd-I5RActdJPEHs5wFtY9YpKiHJ"},
        {"path": "./assets/icons/loading-bar.png", "gdrive_id": "10P6HFW6gfqPn1t1U5XLkL3sWPKqm-Sy6"},
        {"path": "./assets/icons/minus-button.png", "gdrive_id": "1-pZIjCH8dqInNk566ebKNPLv4fcuxqPN"},
        {"path": "./assets/icons/refresh.png", "gdrive_id": "12Yg-XlFOC-UqPITf-SKthqPP3dXAeXAw"},
        {"path": "./assets/icons/repairing.png", "gdrive_id": "1ikDw3X26TfqfiJQ02NWAya6L0lRsjkc5"},
        {"path": "./assets/icons/select.png", "gdrive_id": "1-1OKTcHtWCy5r-6KmjrL8HFjWCPkVRED"},
        {"path": "./assets/icons/settings.png", "gdrive_id": "1v4Ib6xl5R8REXeLMyldpNC0xo6yOxU68"},
        {"path": "./assets/icons/trash.png", "gdrive_id": "1D5rbr9LJPFOsHgqclq_-Js1uaKrFnteL"},
        {"path": "./assets/icons/unselect.png", "gdrive_id": "1CQ6-3Odla165GlUdQLctzGNdFMRJXklD"},
        {"path": "./assets/icons/face-lock.png", "gdrive_id": "1MnZjmYIuAxLrtytWdEUAkApG2NX7aKYS"},
        {"path": "./assets/icons/letter.png", "gdrive_id": "1oTj6pwnMB8nTw46UO9tGCywysKLWYw3E"},
        {"path": "./assets/icons/options.png", "gdrive_id": "1SdsYKemGIn6V53gS2edHj6NfdMWfmvms"},
        {"path": "./assets/icons/check-mark.png", "gdrive_id": "1OPG6dQGaqf81rSuZPYgYUBUcp1l6tik3"},
        {"path": "./assets/icons/down.png", "gdrive_id": "1X_gWRU6JPQ-FrqKIkd-PYG4kNmLK0IGQ"},
        {"path": "./assets/icons/money-bag.png", "gdrive_id": "1gHdVWE-TC_nc_bAR2i5VyTKceqYjN9E1"},
        {"path": "./assets/icons/money-bag-remove.png", "gdrive_id": "16fFMVAfqy8wvqigh21QtAhviKU0pZUkq"},
        {"path": "./assets/icons/rename.png", "gdrive_id": "1dmG_QOzuk-XTdnNGXaF_9gNpXmGh41XP"},
        {"path": "./assets/icons/uncheck-mark.png", "gdrive_id": "1UKL5PitBFL_MpOZS4uYJtq_-iz3JEgdt"},
        {"path": "./assets/icons/copy.png", "gdrive_id": "1dhJa4KfHqYFcnyG8TsdQnuuk_a9nTKuu"},
        {"path": "./assets/icons/enter.png", "gdrive_id": "12ao29hIMouarUsTp_ecJLAW9NPTzFcAJ"},
        {"path": "./assets/icons/import-export.png", "gdrive_id": "1sKd1x7PgGaxhJs8x8hzyfxsGlOQUiuBA"},
        {"path": "./assets/device_info.txt", "gdrive_id": "1RsYzNjsyrpcddqe30OVzKh0TINJEYuEb"},
        {"path": "./assets/list_devices.json", "gdrive_id": "1DmG1yVAxeM3Ou1tUjXDrohknGUHYl5EG"},
    ], key=lambda x: x["path"])